on:
  push:
    branches:
      - 'main'
name: deploy Production
env:
  REGISTRY: docker.pkg.github.com
  IMAGE_NAME: dvoxmario/portafolio-angular
jobs:
  build-and-push-github-registry:
    name: build and push image GitHub Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: chekout
        uses: actions/checkout@v2
      -
        name: Login to github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push github registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

  deploy:
    needs: build-and-push-github-registry
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_IP }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASS }}
        script: |
          cd ${{ secrets.PRODUCTION_PATH }}
          docker-compose pull
          docker-compose up -d